import { Manrope } from "next/font/google";

import "./globals.css";
import HeaderWrapper from "./components/HeadWrapper";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Elite Football Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col w-full items-center">
        <HeaderWrapper />
        {children}
      </body>
    </html>
  );
}
